# Generated by Django 4.2.18 on 2025-03-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_image/profile.jpg",
                upload_to="profile_image",
            ),
        ),
    ]
