# Generated by Django 4.2.18 on 2025-02-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdetails",
            name="asset",
            field=models.ImageField(blank=True, null=True, upload_to="tasks_asset"),
        ),
    ]
