# Generated by Django 4.2.18 on 2025-01-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "types",
                    models.CharField(
                        choices=[
                            ("C", "Concert"),
                            ("H", "Hackathon"),
                            ("S", "Seminar"),
                            ("F", "Fest"),
                        ],
                        max_length=1,
                    ),
                ),
                ("participent", models.CharField(max_length=250)),
                (
                    "events",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.event"
                    ),
                ),
            ],
        ),
    ]
