# Generated by Django 4.2.18 on 2025-02-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_eventdetails_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdetails",
            name="asset",
            field=models.ImageField(
                blank=True,
                default="tasks_asset/default.jpg",
                null=True,
                upload_to="tasks_asset",
            ),
        ),
    ]
