# Generated by Django 4.2.18 on 2025-02-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_eventdetails_asset"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="participant",),
        migrations.DeleteModel(name="Participant",),
    ]
