# Generated by Django 4.2.18 on 2025-02-20 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0004_remove_event_participant_delete_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="participant",
            field=models.ManyToManyField(
                related_name="rsvp_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
