# Generated by Django 4.2.18 on 2025-01-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_participant_event_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdetails",
            name="events",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="tasks.event",
            ),
        ),
    ]
