# Generated by Django 4.2.18 on 2025-01-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_eventdetails_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="participant",
            field=models.ManyToManyField(related_name="events", to="tasks.participant"),
        ),
    ]
